[project]
name = "proxy-optimizer"
authors = ["@ProxyOptimizer"]
description = "Advanced proxy management and optimization smart contract suite"
telemetry = false
requirements = []
[contracts.proxy-registry]
path = "contracts/proxy-registry.clar"
depends_on = []

[contracts.proxy-metrics]
path = "contracts/proxy-metrics.clar"
depends_on = []

[contracts.proxy-rewards]
path = "contracts/proxy-rewards.clar"
depends_on = []

[contracts.proxy-governance]
path = "contracts/proxy-governance.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
